# Generated by Django 3.1 on 2021-01-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=50),
        ),
    ]
